using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._CrimsonCommand.FlavorText;

[GenerateTypedNameReferences]
public sealed partial class NewFlavorText : Control
{
    public Action<string>? OnFlavorTextChanged;
    public Action<string>? OnBackstoryChanged;

    public NewFlavorText()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var loc = IoCManager.Resolve<ILocalizationManager>();

        CFlavorTextInput.Placeholder = new Rope.Leaf(loc.GetString("flavor-text-placeholder"));
        CBackstoryInput.Placeholder = new Rope.Leaf(loc.GetString("backstory-placeholder"));

        CFlavorTextInput.OnTextChanged += _ => OnFlavorTextChanged?.Invoke(Rope.Collapse(CFlavorTextInput.TextRope).Trim());
        CBackstoryInput.OnTextChanged += _ => OnBackstoryChanged?.Invoke(Rope.Collapse(CBackstoryInput.TextRope).Trim());

        TabVisualDescription.OnPressed += _ => SetTab(visual: true);
        TabBackstory.OnPressed += _ => SetTab(visual: false);

        SetTab(visual: true);
    }

    private void SetTab(bool visual)
    {
        PanelVisualDescription.Visible = visual;
        PanelBackstory.Visible = !visual;
        TabVisualDescription.Pressed = visual;
        TabBackstory.Pressed = !visual;
    }
}
